services:
  postgres:
    image: postgres:16.8
    container_name: postgres_memoria_dev
    ports:
      - "5432:5432"
    volumes:
      - postgresdev_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - dev.env
    networks:
      - memoriadev_network

volumes:
  postgresdev_data:
    driver: local

networks:
  memoriadev_network:
    driver: bridge
