version: '3.8'

services:
  postgres:
    image: postgres:16.8
    container_name: postgres_memoria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    restart: always
    networks:
      - memoria_network

  memoria:
    image: memoria
    container_name: memoria
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - memoria_network

volumes:
  postgres_data:
    driver: local

networks:
  memoria_network:
    driver: bridge
